root: true
parser: '@typescript-eslint/parser'
parserOptions:
  project: 'tsconfig.eslint.json'
  tsconfigRootDir: ./
extends: 
  - 'moon'
  - 'moon/node'
rules:
  'import/no-unresolved': 'off'
  'import/no-useless-path-segments': 'off'
overrides:
  - files: ['*.config.js', '.eslintrc.js']
    rules:
      'unicorn/prefer-module': 'off'
      'import/no-commonjs': 'off'
      'sort-keys': 'off'